import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/app/NavBar";
import { ReactNode } from "react";
import { Container, Theme } from "@radix-ui/themes";
import AuthProvider from "@/app/auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import prisma from "@/prisma/client";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getIssueStatus = () => {
  return prisma.issue.count({
    where: {
      assignedToUserId: {
        not: {
          equals: null,
        },
      },
    },
    select: {
      status: true,
    },
  });
};

const RootLayout = async ({ children }: { children: ReactNode }) => {
  const count = await getIssueStatus();

  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme appearance="dark" accentColor="plum">
              <NavBar count={count.status} />
              <main className="p-5">
                <Container>{children}</Container>
              </main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
