import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React, { ReactNode } from "react";
import { Container, Theme } from "@radix-ui/themes";
import AuthProvider from "@/app/auth/Provider";
import { QueryClientProvider, RecoilContextProvider } from "@/app/providers";
import { NavbarWrapper } from "@/app/components";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <RecoilContextProvider>
              <Theme appearance="dark" accentColor="sky">
                <NavbarWrapper />
                <main className="p-5">
                  <Container>{children}</Container>
                </main>
              </Theme>
            </RecoilContextProvider>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
